{% set version = "2.2.0" %}

package:
  name: mgwr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mgwr/mgwr-{{ version }}.tar.gz
  sha256: fc5d9a9040f80e0396cf3ecba2582f672988f9db3b1c705c77c45fb94201fe87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - libpysal >=4.0.0
    - numpy >=1.3
    - scipy >=0.11
    - spglm >=1.0.6
    - spreg

test:
  imports:
    - mgwr

about:
  home: https://github.com/pysal/mgwr
  license: BSD-3-Clause
  license_file: LICENSE
  # https://github.com/pysal/mgwr/issues/25
  # license_file: 
  summary: Multiscale geographically weighted regression
  doc_url: https://mgwr.readthedocs.io
  dev_url: http://github.com/pysal/mgwr

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
    - martinfleis
    - ocefpaf
