{% set version = "2.0.0" %}

package:
  name: mgwr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mgwr/mgwr-{{ version }}.tar.gz
  sha256: 957e85d082ed7bfc36a3f03420dfa67abd1b4b2e799d94892448648528a42b31

build:
  number: 0
  # is pure python, uses 2to3, and depends on libpysal that is py3k only!
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - libpysal
    - numpy
    - scipy
    - spglm
    - spreg

test:
  imports:
    - mgwr

about:
  home: https://github.com/pysal/mgwr
  license: BSD-3-Clause
  # https://github.com/pysal/mgwr/issues/25
  # license_file: 
  summary: 'Multiscale geographically weighted regression'

extra:
  recipe-maintainers:
    - ocefpaf
