{% set version = "2.1.2" %}

package:
  name: mgwr
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mgwr/mgwr-{{ version }}.tar.gz
  sha256: cc5e845e70f169a0eb9aaf2cb27391cecb6cff27ca4916f7e9f7bba19338d26d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - libpysal >=4.0.0
    - numpy >=1.3
    - scipy >=0.11
    - spglm >=1.0.6
    - spreg

test:
  imports:
    - mgwr

about:
  home: https://github.com/pysal/mgwr
  license: BSD-3-Clause
  license_file: LICENSE
  # https://github.com/pysal/mgwr/issues/25
  # license_file: 
  summary: Multiscale geographically weighted regression

extra:
  recipe-maintainers:
    - jGaboardi
    - knaaptime
    - martinfleis
    - ocefpaf
